/**
 * constants.js — Catálogo de apps populares pre-configuradas para el Discover.
 * 20 servicios populares listos para instalar con 1 clic.
 */

export const CATEGORIES = [
  { id: 'all',            label_es: 'Todas',          label_en: 'All' },
  { id: 'trabajo',        label_es: 'Trabajo',         label_en: 'Work' },
  { id: 'social',         label_es: 'Social',          label_en: 'Social' },
  { id: 'entretenimiento',label_es: 'Entretenimiento', label_en: 'Entertainment' },
  { id: 'desarrollo',     label_es: 'Desarrollo',      label_en: 'Development' },
  { id: 'ia',             label_es: 'IA & Productividad', label_en: 'AI & Productivity' },
  { id: 'general',        label_es: 'General',         label_en: 'General' },
];

export const APP_TEMPLATES = [
  {
    id: 'streaming',
    label_es: 'Streaming',
    label_en: 'Streaming',
    category: 'entretenimiento',
    accent: '#8b5cf6',
    description_es: 'Video, musica y entretenimiento con PiP, controles y bloqueo agresivo de anuncios.',
    description_en: 'Video, music and entertainment with PiP, controls and aggressive ad blocking.',
    config: {
      openMode: 'normal',
      adblockEnabled: true,
      toolbar: {
        enabled: true,
        buttons: ['back', 'forward', 'reload', 'home', 'pip', 'notes'],
      },
      shortcuts: {
        enabled: true,
        bindings: {
          reload: 'Ctrl+R',
          home: 'Alt+Home',
          pip: 'Ctrl+Shift+P',
        },
      },
      windowConfig: { width: 1320, height: 820 },
    },
  },
  {
    id: 'ia',
    label_es: 'IA',
    label_en: 'AI',
    category: 'ia',
    accent: '#10b981',
    description_es: 'Asistentes de IA con notas, home rapido, scripts y entorno enfocado.',
    description_en: 'AI assistants with notes, quick home, scripts and a focused workspace.',
    config: {
      openMode: 'normal',
      adblockEnabled: true,
      toolbar: {
        enabled: true,
        buttons: ['back', 'forward', 'reload', 'home', 'notes'],
      },
      shortcuts: {
        enabled: true,
        bindings: {
          reload: 'Ctrl+R',
          home: 'Alt+Home',
          notes: 'Ctrl+Shift+N',
        },
      },
      windowConfig: { width: 1240, height: 820 },
    },
  },
  {
    id: 'productividad',
    label_es: 'Productividad',
    label_en: 'Productivity',
    category: 'trabajo',
    accent: '#06b6d4',
    description_es: 'Trabajo diario con notas, navegacion limpia y sesiones persistentes.',
    description_en: 'Daily work with notes, clean navigation and persistent sessions.',
    config: {
      openMode: 'normal',
      adblockEnabled: true,
      toolbar: {
        enabled: true,
        buttons: ['back', 'forward', 'reload', 'home', 'notes'],
      },
      shortcuts: {
        enabled: true,
        bindings: {
          reload: 'Ctrl+R',
          home: 'Alt+Home',
        },
      },
      windowConfig: { width: 1280, height: 840 },
    },
  },
  {
    id: 'desarrollo',
    label_es: 'Desarrollo',
    label_en: 'Development',
    category: 'desarrollo',
    accent: '#f97316',
    description_es: 'Herramientas tecnicas con DevTools, recarga rapida y notas por app.',
    description_en: 'Technical tools with DevTools, quick reload and per-app notes.',
    config: {
      openMode: 'normal',
      adblockEnabled: true,
      toolbar: {
        enabled: true,
        buttons: ['back', 'forward', 'reload', 'home', 'devtools', 'notes'],
      },
      shortcuts: {
        enabled: true,
        bindings: {
          reload: 'Ctrl+R',
          home: 'Alt+Home',
          devtools: 'Ctrl+Shift+I',
          notes: 'Ctrl+Shift+N',
        },
      },
      windowConfig: { width: 1360, height: 860 },
    },
  },
];

export const TEMPLATE_BY_CATEGORY = {
  entretenimiento: 'streaming',
  ia: 'ia',
  trabajo: 'productividad',
  desarrollo: 'desarrollo',
};

// Shorthand para no repetir iconType:'favicon' en cada entrada
const fav = (id, name, url, category, iconColor, description_es, description_en, featured = false, rating = 4.2) =>
  ({ id, name, url, category, iconType: 'favicon', iconColor, description_es, description_en, featured, rating });

/** @type {AppCatalogEntry[]} */
export const DISCOVER_APPS = [
  // ── IA & Productividad ────────────────────────────────────────────────────
  {
    id:          'catalog_chatgpt',
    name:        'ChatGPT',
    url:         'https://chat.openai.com',
    category:    'ia',
    iconType:    'favicon',
    iconValue:   'GPT',
    iconColor:   '#10a37f',
    description_es: 'El asistente de IA más popular del mundo.',
    description_en: 'The world\'s most popular AI assistant.',
    featured:    true,
    rating:      4.9,
  },
  {
    id:          'catalog_claude',
    name:        'Claude',
    url:         'https://claude.ai',
    category:    'ia',
    iconType:    'favicon',
    iconValue:   'Cl',
    iconColor:   '#d97706',
    description_es: 'Asistente de IA de Anthropic, experto en razonamiento.',
    description_en: 'Anthropic\'s AI assistant, expert in reasoning.',
    featured:    true,
    rating:      4.8,
  },
  {
    id:          'catalog_notebooklm',
    name:        'NotebookLM',
    url:         'https://notebooklm.google.com',
    category:    'ia',
    iconType: 'favicon',
    iconValue:   'NB',
    iconColor:   '#4285f4',
    description_es: 'Notebook inteligente de Google con IA generativa.',
    description_en: 'Google\'s AI-powered smart notebook.',
    featured:    true,
  },
  {
    id:          'catalog_perplexity',
    name:        'Perplexity',
    url:         'https://perplexity.ai',
    category:    'ia',
    iconType: 'favicon',
    iconValue:   'PP',
    iconColor:   '#7c3aed',
    description_es: 'Motor de búsqueda potenciado por IA en tiempo real.',
    description_en: 'Real-time AI-powered search engine.',
    featured:    false,
  },

  // ── Trabajo & Productividad ────────────────────────────────────────────────
  {
    id:          'catalog_notion',
    name:        'Notion',
    url:         'https://notion.so',
    category:    'trabajo',
    iconType: 'favicon',
    iconValue:   'N',
    iconColor:   '#374151',
    description_es: 'Tu espacio de trabajo todo en uno para notas y proyectos.',
    description_en: 'Your all-in-one workspace for notes and projects.',
    featured:    true,
  },
  {
    id:          'catalog_figma',
    name:        'Figma',
    url:         'https://figma.com',
    category:    'trabajo',
    iconType: 'favicon',
    iconValue:   'Fig',
    iconColor:   '#f24e1e',
    description_es: 'Diseño colaborativo en tiempo real para equipos.',
    description_en: 'Real-time collaborative design for teams.',
    featured:    true,
  },
  {
    id:          'catalog_linear',
    name:        'Linear',
    url:         'https://linear.app',
    category:    'trabajo',
    iconType: 'favicon',
    iconValue:   'Li',
    iconColor:   '#5e6ad2',
    description_es: 'Gestión de proyectos de software ultra rápida.',
    description_en: 'Blazing fast software project management.',
    featured:    false,
  },
  {
    id:          'catalog_trello',
    name:        'Trello',
    url:         'https://trello.com',
    category:    'trabajo',
    iconType: 'favicon',
    iconValue:   'Tr',
    iconColor:   '#0052cc',
    description_es: 'Tableros Kanban para organizar cualquier proyecto.',
    description_en: 'Kanban boards for organizing any project.',
    featured:    false,
  },
  {
    id:          'catalog_asana',
    name:        'Asana',
    url:         'https://app.asana.com',
    category:    'trabajo',
    iconType: 'favicon',
    iconValue:   'As',
    iconColor:   '#f06a6a',
    description_es: 'Gestión de tareas y flujos de trabajo en equipo.',
    description_en: 'Team task and workflow management.',
    featured:    false,
  },
  {
    id:          'catalog_canva',
    name:        'Canva',
    url:         'https://canva.com',
    category:    'trabajo',
    iconType: 'favicon',
    iconValue:   'Ca',
    iconColor:   '#00c4cc',
    description_es: 'Diseño gráfico fácil para no diseñadores.',
    description_en: 'Easy graphic design for non-designers.',
    featured:    false,
  },

  // ── Desarrollo ────────────────────────────────────────────────────────────
  {
    id:          'catalog_github',
    name:        'GitHub',
    url:         'https://github.com',
    category:    'desarrollo',
    iconType: 'favicon',
    iconValue:   'GH',
    iconColor:   '#24292e',
    description_es: 'La plataforma de desarrollo colaborativo líder.',
    description_en: 'The leading collaborative development platform.',
    featured:    true,
  },
  {
    id:          'catalog_vercel',
    name:        'Vercel',
    url:         'https://vercel.com',
    category:    'desarrollo',
    iconType: 'favicon',
    iconValue:   'V▲',
    iconColor:   '#000000',
    description_es: 'Deploy y hosting instantáneo para aplicaciones web.',
    description_en: 'Instant deploy and hosting for web applications.',
    featured:    false,
  },
  {
    id:          'catalog_supabase',
    name:        'Supabase',
    url:         'https://supabase.com/dashboard',
    category:    'desarrollo',
    iconType: 'favicon',
    iconValue:   'SB',
    iconColor:   '#3ecf8e',
    description_es: 'Alternativa open source a Firebase con PostgreSQL.',
    description_en: 'Open source Firebase alternative with PostgreSQL.',
    featured:    false,
  },

  // ── Social ────────────────────────────────────────────────────────────────
  {
    id:          'catalog_whatsapp',
    name:        'WhatsApp Web',
    url:         'https://web.whatsapp.com',
    category:    'social',
    iconType: 'favicon',
    iconValue:   'WA',
    iconColor:   '#25d366',
    description_es: 'WhatsApp en tu escritorio con sesiones aisladas.',
    description_en: 'WhatsApp on your desktop with isolated sessions.',
    featured:    true,
  },
  {
    id:          'catalog_slack',
    name:        'Slack',
    url:         'https://app.slack.com',
    category:    'social',
    iconType: 'favicon',
    iconValue:   'Sl',
    iconColor:   '#4a154b',
    description_es: 'Comunicación en equipo centrada en canales.',
    description_en: 'Channel-based team communication.',
    featured:    false,
  },
  {
    id:          'catalog_discord',
    name:        'Discord',
    url:         'https://discord.com/app',
    category:    'social',
    iconType: 'favicon',
    iconValue:   'Dc',
    iconColor:   '#5865f2',
    description_es: 'Comunidades de voz, video y texto.',
    description_en: 'Voice, video and text communities.',
    featured:    false,
  },
  {
    id:          'catalog_x',
    name:        'X (Twitter)',
    url:         'https://x.com',
    category:    'social',
    iconType: 'favicon',
    iconValue:   'X',
    iconColor:   '#000000',
    description_es: 'La red de microblogging y noticias en tiempo real.',
    description_en: 'The microblogging and real-time news network.',
    featured:    false,
  },

  // ── Entretenimiento ───────────────────────────────────────────────────────
  {
    id:          'catalog_youtube',
    name:        'YouTube',
    url:         'https://youtube.com',
    category:    'entretenimiento',
    iconType:    'favicon',
    iconValue:   'YT',
    iconColor:   '#ff0000',
    description_es: 'La mayor plataforma de video del mundo.',
    description_en: 'The world\'s largest video platform.',
    featured:    true,
    rating:      4.8,
  },
  {
    id:          'catalog_netflix',
    name:        'Netflix',
    url:         'https://netflix.com',
    category:    'entretenimiento',
    iconType:    'favicon',
    iconValue:   'N',
    iconColor:   '#e50914',
    description_es: 'Streaming de series y películas bajo demanda.',
    description_en: 'On-demand movie and series streaming.',
    featured:    false,
    rating:      4.6,
  },
  {
    id:          'catalog_spotify',
    name:        'Spotify',
    url:         'https://open.spotify.com',
    category:    'entretenimiento',
    iconType:    'favicon',
    iconValue:   'Sp',
    iconColor:   '#1db954',
    description_es: 'Música, podcasts y audiolibros en streaming.',
    description_en: 'Music, podcasts and audiobooks streaming.',
    featured:    false,
    rating:      4.7,
  },
  {
    id:          'catalog_twitch',
    name:        'Twitch',
    url:         'https://twitch.tv',
    category:    'entretenimiento',
    iconType:    'favicon',
    iconValue:   'Tw',
    iconColor:   '#9146ff',
    description_es: 'Streaming en vivo de videojuegos y contenido en tiempo real.',
    description_en: 'Live streaming platform for gaming and real-time content.',
    featured:    false,
    rating:      4.4,
  },

  // ── Trabajo ampliado ──────────────────────────────────────────────────────
  {
    id:          'catalog_gmail',
    name:        'Gmail',
    url:         'https://mail.google.com',
    category:    'trabajo',
    iconType:    'favicon',
    iconValue:   'GM',
    iconColor:   '#ea4335',
    description_es: 'El cliente de correo electrónico de Google, aislado del navegador.',
    description_en: 'Google\'s email client, isolated from your browser.',
    featured:    true,
    rating:      4.8,
  },
  {
    id:          'catalog_outlook',
    name:        'Outlook',
    url:         'https://outlook.live.com',
    category:    'trabajo',
    iconType:    'favicon',
    iconValue:   'OL',
    iconColor:   '#0078d4',
    description_es: 'Correo y calendario de Microsoft en tu escritorio.',
    description_en: 'Microsoft mail and calendar on your desktop.',
    featured:    false,
    rating:      4.3,
  },
  {
    id:          'catalog_gcal',
    name:        'Google Calendar',
    url:         'https://calendar.google.com',
    category:    'trabajo',
    iconType:    'favicon',
    iconValue:   'GC',
    iconColor:   '#4285f4',
    description_es: 'Tu agenda y calendario de Google siempre a mano.',
    description_en: 'Your Google calendar always within reach.',
    featured:    false,
    rating:      4.6,
  },
  {
    id:          'catalog_teams',
    name:        'Microsoft Teams',
    url:         'https://teams.microsoft.com',
    category:    'trabajo',
    iconType:    'favicon',
    iconValue:   'MT',
    iconColor:   '#6264a7',
    description_es: 'Chat, videollamadas y colaboración en equipo de Microsoft.',
    description_en: 'Microsoft\'s team chat, video calls and collaboration.',
    featured:    false,
    rating:      4.1,
  },
  {
    id:          'catalog_loom',
    name:        'Loom',
    url:         'https://loom.com',
    category:    'trabajo',
    iconType:    'favicon',
    iconValue:   'Lo',
    iconColor:   '#625df5',
    description_es: 'Graba y comparte videos explicativos de forma instantánea.',
    description_en: 'Record and share explanatory videos instantly.',
    featured:    false,
    rating:      4.5,
  },
  {
    id:          'catalog_miro',
    name:        'Miro',
    url:         'https://miro.com/app/',
    category:    'trabajo',
    iconType:    'favicon',
    iconValue:   'Mi',
    iconColor:   '#ffd02f',
    description_es: 'Pizarra colaborativa online para equipos distribuidos.',
    description_en: 'Online collaborative whiteboard for distributed teams.',
    featured:    false,
    rating:      4.6,
  },
  {
    id:          'catalog_monday',
    name:        'Monday.com',
    url:         'https://monday.com',
    category:    'trabajo',
    iconType:    'favicon',
    iconValue:   'Mo',
    iconColor:   '#ff3d57',
    description_es: 'Plataforma de gestión de trabajo y proyectos visual.',
    description_en: 'Visual work and project management platform.',
    featured:    false,
    rating:      4.3,
  },
  {
    id:          'catalog_todoist',
    name:        'Todoist',
    url:         'https://app.todoist.com',
    category:    'trabajo',
    iconType:    'favicon',
    iconValue:   'TD',
    iconColor:   '#db4035',
    description_es: 'La app de tareas y productividad personal más popular.',
    description_en: 'The most popular personal tasks and productivity app.',
    featured:    false,
    rating:      4.6,
  },

  // ── Social ampliado ───────────────────────────────────────────────────────
  {
    id:          'catalog_telegram',
    name:        'Telegram Web',
    url:         'https://web.telegram.org',
    category:    'social',
    iconType:    'favicon',
    iconValue:   'TG',
    iconColor:   '#2aabee',
    description_es: 'Mensajería segura y rápida, aislada del navegador.',
    description_en: 'Fast and secure messaging, isolated from your browser.',
    featured:    false,
    rating:      4.7,
  },
  {
    id:          'catalog_linkedin',
    name:        'LinkedIn',
    url:         'https://linkedin.com',
    category:    'social',
    iconType:    'favicon',
    iconValue:   'Li',
    iconColor:   '#0a66c2',
    description_es: 'La red profesional más grande del mundo.',
    description_en: 'The world\'s largest professional network.',
    featured:    false,
    rating:      4.1,
  },
  {
    id:          'catalog_reddit',
    name:        'Reddit',
    url:         'https://reddit.com',
    category:    'social',
    iconType:    'favicon',
    iconValue:   'Re',
    iconColor:   '#ff4500',
    description_es: 'Comunidades de discusión sobre cualquier tema imaginable.',
    description_en: 'Discussion communities about any imaginable topic.',
    featured:    false,
    rating:      4.3,
  },

  // ── Desarrollo ampliado ───────────────────────────────────────────────────
  {
    id:          'catalog_gitlab',
    name:        'GitLab',
    url:         'https://gitlab.com',
    category:    'desarrollo',
    iconType:    'favicon',
    iconValue:   'GL',
    iconColor:   '#fc6d26',
    description_es: 'Plataforma DevOps completa: código, CI/CD, y despliegue.',
    description_en: 'Complete DevOps platform: code, CI/CD, and deployment.',
    featured:    false,
    rating:      4.4,
  },
  {
    id:          'catalog_railway',
    name:        'Railway',
    url:         'https://railway.app',
    category:    'desarrollo',
    iconType:    'favicon',
    iconValue:   'Ry',
    iconColor:   '#0b0d0e',
    description_es: 'Deploy de apps y bases de datos en segundos.',
    description_en: 'Deploy apps and databases in seconds.',
    featured:    false,
    rating:      4.5,
  },
  {
    id:          'catalog_planetscale',
    name:        'PlanetScale',
    url:         'https://app.planetscale.com',
    category:    'desarrollo',
    iconType:    'favicon',
    iconValue:   'PS',
    iconColor:   '#000000',
    description_es: 'Base de datos MySQL serverless con branching de esquemas.',
    description_en: 'Serverless MySQL database with schema branching.',
    featured:    false,
    rating:      4.4,
  },
];

/** Versión de la aplicación */
export const APP_VERSION = '3.1.0';
export const APP_NAME    = 'AppSpawner';
export const APP_BUILD   = 'Premium Build';
